### ISSUE TITLE
Impossible to route or rewrite requests for static files

### ISSUE THREAD

**Issue by rgrove** [manveru/ramaze#1]
Since routes are evaluated after static file lookups in Ramaze, it's impossible to route or rewrite a request for a static file. It was possible in pre-Innate Ramaze, so this is a regression.

There's a simple test case to reproduce this issue at http://gist.github.com/101797

**Comment by clivecrous** [comment]
I tried your code exactly as you've put it with the current repository versions of rack, innate and ramaze and "It worked!"

**Comment by clivecrous** [comment]
http://gist.github.com/101922

**Comment by rgrove** [comment]
You most likely didn't create the public/test.txt file. If that file doesn't exist, the route will work fine. When it does exist, the route never gets evaluated.

http://gist.github.com/101926

**Comment by clivecrous** [comment]
ahhhhh, this is why I should never do anything online with a hangover :( sorry

**Comment by clivecrous** [comment]
After giving this some thought, I'm very interested to hear what manveru says about this. I actually prefer the way it works now, routing only if a static file is not found ... but I won't use this often enough to really care which way is "more correct". I'm just wondering if manveru did this on purpose or if it's accidental regression.

**Comment by rgrove** [comment]
Already discussed this with manveru on #ramaze, and I agree with him that this is probably the preferred behavior for performance reasons, but since it's different from pre-Innate Ramaze and could break existing apps (it broke mine), I wanted to leave the bug open at least until the difference is documented.

**Comment by manveru** [comment]
OK, thanks guys :)
I won't change this behaviour anymore unless someone has a killer-argument.
The way Ramaze handles it now out-of-the-box is closer to the way real deployment is setup, and should make it easier to anticipate the environment the app has to run in.
Now looking for places where we could document that... the Route/Rewrite code?

**Comment by rgrove** [comment]
That seems logical. Also might make sense to explain Ramaze's hands-off approach to static file serving elsewhere in the docs, like where public directories are discussed.

**Comment by manveru** [comment]
OK, I'll write a bit about it today when i find some time, will close the bug when it's done.

**Comment by clivecrous** [comment]
I like that github has bug tracking now :D
