### ISSUE TITLE
anchor's escaping of arguments not working as expected

### ISSUE THREAD

**Issue by dominikh** [manveru/ramaze#2]
When using Controller#a, only the third+ arguments are escaped whereas one might expect it to also escape the second one.

Example: 
SomeController.a('label', 'my arguments') # returns a href of "/mapping/my arguments"
SomeController.a('label', '', 'my arguments') # returns a href of "/mapping/my+arguments"

**Comment by manveru** [comment]
That is because the second argument is assumed to be the name of your action, '/' in this case.
If you think this is really a bug, please consider trying to patch it and run the specs.
