### ISSUE TITLE
example not found "require 'rubygems'"  in examples/basic/gestalt.rb

### ISSUE THREAD

**Issue by haru01** [manveru/ramaze#3]
Hi 

I learn ramaze.
cann't start examples/basic/gestalt.rb

must require 'rubygems' ??

**Comment by manveru** [comment]
Yes, either you start with `ruby -rubygems`, or use `RUBYOPT=-rubygems ruby`.
I won't add the require "rubygems" to new examples anymore, as it's not needed in Ruby 1.9 anymore.
