### ISSUE TITLE
Tutorial: "File.expand_path(Ramaze::BASEDIR..." gave error msg

### ISSUE THREAD

**Issue by jenko** [manveru/ramaze#4]
said msg: W [2009-08-07 15:40:59 $28389]  WARN | : Ramaze::BASEDIR is deprecated, use ROOT instead
NoMethodError: undefined method `constant' for Ramaze:Module
    from /usr/lib/ruby/gems/1.8/gems/ramaze-2009.07/lib/ramaze/snippets/ramaze/deprecated.rb:18:in`const_missing'
    from (irb):3

(and, most importantly, did not give path to "todolist.html")

This worked:

File.expand_path(Ramaze::ROOT + '/../examples/app/todolist')
=> "/usr/lib/ruby/gems/1.8/gems/ramaze-2009.07/examples/app/todolist"

**Comment by manveru** [comment]
Generated latest from asciidoc, see http://ramaze.net/todolist.html and http://github.com/manveru/ramaze/commit/0b4d33d6a3d8ae32374dda3cbb4620865ee9f8bc
