### ISSUE TITLE
Problem with parsing hash argument in Nagoro template

### ISSUE THREAD

**Issue by pejuko** [manveru/ramaze#6]
In the Nagoro template I have line similar to:
  #{render_properties('Author', 50, :element => @article)}
and as the result I get this error output:
Scanner didn't move: #<Nagoro::Scanner 1439/10470 "...ent =" @ "> @ar..."> In: ./src/template/article_form.xhtml

**Comment by manveru** [comment]
Sorry, but I cannot reproduce this.
Can you add a failing spec to Nagoro?

**Comment by pejuko** [comment]
I've added and sent you a pull request
